spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'root'
    platform: mysql
    url: jdbc:mysql://localhost:3306/casadocodigodb?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

## Configuração para o Spring lançar os Erros ##
#server:
#  error:
#    include-message: always
#    include-binding-errors: always


